# Generated by Django 5.1.3 on 2024-11-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_contact_remove_appointment_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='subject',
        ),
    ]
